apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

//apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.gms.google-services'

android {
    namespace = "com.icaali.kalenderpuasasunnah"
    compileSdk 35
    compileOptions {
        targetCompatibility JavaVersion.VERSION_17
    }
    defaultConfig {
        applicationId "com.icaali.kalenderpuasasunnah"
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 18
        versionName "18.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        release {
            storeFile file("../kalenderPuasa-new.jks")
            storePassword "5elamanya"
            keyAlias "key0"
            keyPassword "5elamanya"
        }
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    implementation 'androidx.activity:activity-ktx:1.10.0'
    implementation 'androidx.fragment:fragment-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'com.google.android.material:material:1.12.0'

    implementation 'com.google.android.gms:play-services-ads:23.1.0'
    implementation 'com.android.billingclient:billing-ktx:7.1.1'

    implementation 'com.github.kizitonwose:CalendarView:0.3.2'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.firebase:firebase-messaging:24.0.0'
    
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation group: 'com.github.msarhan', name: 'ummalqura-calendar', version: '1.1.9'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
